### ISSUE TITLE
please delete....it's fixed.

### ISSUE THREAD

**Issue by itsmetoolala** [ReneSchwarzer/InventoryExpress#3]
please delete....it's fixed.

**Comment by ReneSchwarzer** [comment]
Hallo itsmetoolala,


danke für das Feedback. Leider sind Sie die einzige Person, welche das Programm verendet. Ich habe das Programm damals für Windows Phone geschrieben und auch einige Zeit selber für meine Computersammlung benutzt. Mittlerweile bin ich dabei das Programm als Webanwendung umzuschreiben. Für die alte Windows-Version fehlt mir die Zeit, diese weiterhin zu pflegen.

Es tut mir leid, wenn ich nicht weiter helfen kann.

Die Inventargegenstände werden Sie nur durch einzelnes löschen wieder los. Alternativ können Sie unter Windows das Installationsverzeichnis suchen und dort die Dateien (z.B. C:\Users\<Benutzer>\AppData\Local\Packages\4117R.Schwarzer.InventoryExpress_ntrwvj0z0mke0\LocalState) löschen.


Gruß
René


Von: ***@***.***>
Gesendet: Freitag, 31. März 2023 14:36
An: ***@***.***>
Cc: ***@***.***>
Betreff: [ReneSchwarzer/InventoryExpress] "Tags" funktionieren nicht in der Suche. Beispieldaten löschen? Theme ändern? (Issue #3)


Hallo Herr Rene Schwarzer!

Da es ein deutsches Programm ist, gehe ich davon aus, dass ich nicht in Englisch schreiben muss. ;-)

Vorab: Ein sehr gutes und einfaches Programm, wonach ich lange gesucht habe. Einfach perfekt um den ganzen Kleinkram im eigenen Haushalt wegzuverfrachten, ohne dass man sich Wochen/Monate/Jahre danach fragt: "Wo war'n das noch gleich?" ;-)
Gefunden und installiert im MS Store!

Danke hierfür!

Allerdings möchte man ja einen Artikel benennen, der aber noch Untergruppen hat. Zum Beispiel packe ich in Standort "Karton 1" eine Tüte mit Nähgarn und bestimmten (aber einigen) Nähartikeln hinein, die ich nur als Nähtütchen bezeichnen möchte.
Name: Nähtütchen.
Standort: Kiste 1
Alles gut soweit.

Aber im Tütchen sind ja weitere Dinge, die ich (wie allgemein gewohnt) unter "Tags" aufführe.
So gehe ich davon aus, wie überall im Internet auch gewohnt, dass ich nicht nur Namen suchen und finden kann (was ja auch gut klappt), sondern eben auch die wichtigen Tags. Ohne Tags nützt mir das Programm herzlich wenig.

Daher gehe ich davon aus, dass dies wohl eher ein Bug ist?
Also Namen- bzw. Titelsuche ist funktionstüchtig, aber nicht die Tagsuche.

Wäre ganz lieb von Ihnen, wenn Sie dies nachbessern oder ggfs auch einarbeiten können, dass man auch nach den Tags suchen kann.
Auch ein Hilfetext hierzu im Programm wäre nützlich. Bspw. Tags trennen mit Komma (oder Leerzeichen).

Vielen Dank im Voraus!

Liebe Grüße, itsmetoolala

PS: Könnte man bitte bitte auch das "Theme/Design" selbst anpassen oder es zumindest auf Windows Hell stellen? Der schwarze Hintergrund ist auf die Dauer doch ein sehr anstrengend für meine alten Äuglein. ^-^

PPS: Ich habe die Beispieldaten geladen, welche unter "Hilfe" zu finden sind. Das ist prima. Danke hierfür; denn es hilft zu verstehen!
Aber wie kann ich denn nun alles wieder löschen und meine neue leere Datenbank erstellen?
